// Shot bundler: `tools/shot/main.ts` → `out/shot/shot.mjs`.
//
// The same pattern as the VS Code smoke (`esbuild.smoke.mjs`): the tooling is
// TypeScript, type-checked by `tsconfig.tools.json` and linted, and esbuild turns
// it into one node-runnable file. `playwright` and `ws` stay external — they are
// resolved from `node_modules` at runtime, which is where their native bits live.
//
// The `banner` injects a `require` for bundled CJS packages (`ws`) that esbuild
// rewrites into a `__require` shim inside an ESM output.

import { mkdirSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import esbuild from 'esbuild';

const root = path.dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes('--watch');

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [path.join(root, 'tools/shot/main.ts')],
  outfile: path.join(root, 'out/shot/shot.mjs'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: true,
  logLevel: 'info',
  external: ['playwright', 'ws'],
  banner: {
    js: [
      '// generated by esbuild.shot.mjs — the wing web screenshot runner. Do not edit.',
      "import { createRequire as __wingCreateRequire } from 'node:module';",
      'const require = __wingCreateRequire(import.meta.url);',
    ].join('\n'),
  },
};

mkdirSync(path.join(root, 'out/shot'), { recursive: true });

if (watch) {
  const context = await esbuild.context(options);
  await context.watch();
  process.stdout.write('[esbuild] watching tools/shot/main.ts → out/shot/shot.mjs\n');
} else {
  await esbuild.build(options);
}
