//! User configuration — load from `$WING_HOME/tui/config.yaml`.
//!
//! Missing file → silent defaults. Parse error → warn + defaults.

pub mod colors;
pub mod rendering;

use std::path::PathBuf;

use ratatui::style::Color;
use serde::Deserialize;
use serde::Serialize;

use self::colors::parse_color;
use self::rendering::RenderingConfig;

/// Semantic color palette — 9 slots covering all UI components.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ColorsConfig {
    /// Brand color: logo, commands, links, code, popups.
    pub accent: String,
    /// Primary text: messages, model name, input.
    pub text: String,
    /// Thinking: agent reasoning content (more prominent than dim).
    pub thinking: String,
    /// Tool result: tool call output, diff context (secondary data).
    pub tool_result: String,
    /// Secondary text: bullets, borders, gutters, separators.
    pub dim: String,
    /// Success: diff+, blockquote, token low.
    pub success: String,
    /// Warning: pending, token mid.
    pub warning: String,
    /// Danger: diff-, error, token high.
    pub danger: String,
    /// Surface: user message background.
    pub surface: String,
}

impl Default for ColorsConfig {
    fn default() -> Self {
        Self {
            accent: "cyan".into(),
            text: "white".into(),
            thinking: "gray".into(),
            tool_result: "dark_gray".into(),
            dim: "dark_gray".into(),
            success: "green".into(),
            warning: "yellow".into(),
            danger: "red".into(),
            surface: "#343541".into(),
        }
    }
}

/// Layout configuration section.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct LayoutConfig {
    /// Maximum input area lines.
    pub max_input_lines: usize,
    /// Maximum visible rows in selection popup.
    pub max_popup_rows: usize,
    /// Context lines around diff hunks.
    pub diff_context: usize,
    /// Maximum tool result output lines.
    pub tool_output_max: usize,
}

impl Default for LayoutConfig {
    fn default() -> Self {
        Self {
            max_input_lines: 10,
            max_popup_rows: 8,
            diff_context: 3,
            tool_output_max: 10,
        }
    }
}

/// Gateway connection configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct GatewayConfig {
    /// Gateway host address.
    pub host: String,
    /// Gateway port.
    pub port: u16,
}

impl Default for GatewayConfig {
    fn default() -> Self {
        Self {
            host: "127.0.0.1".into(),
            port: 32523,
        }
    }
}

/// Top-level application configuration.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct AppConfig {
    pub colors: ColorsConfig,
    pub layout: LayoutConfig,
    pub rendering: RenderingConfig,
    pub gateway: GatewayConfig,
}

impl AppConfig {
    /// Load configuration from `$WING_HOME/tui/config.yaml`.
    ///
    /// Returns defaults if the file doesn't exist or fails to parse.
    pub fn load() -> Self {
        let Some(path) = config_path() else {
            tracing::warn!("cannot determine config directory, using defaults");
            return Self::default();
        };
        match std::fs::read_to_string(&path) {
            Ok(content) => match serde_yaml::from_str::<AppConfig>(&content) {
                Ok(cfg) => {
                    tracing::info!(?path, "loaded config");
                    cfg
                }
                Err(e) => {
                    tracing::warn!(?path, %e, "failed to parse config, using defaults");
                    Self::default()
                }
            },
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                tracing::debug!(?path, "no config file, using defaults");
                Self::default()
            }
            Err(e) => {
                tracing::warn!(?path, %e, "failed to read config, using defaults");
                Self::default()
            }
        }
    }

    /// Serialize to YAML string (for `--dump-config`).
    pub fn to_yaml(&self) -> String {
        // Use serde_yaml for structure, then prepend header comment.
        let yaml = serde_yaml::to_string(self).unwrap_or_default();
        format!(
            "# wing configuration\n\
             # Generated by `wing tui --dump-config`\n\
             # Place at $WING_HOME/tui/config.yaml (default: ~/.wing/tui/config.yaml)\n\
             #\n\
             # Colors: named ANSI (e.g. \"cyan\", \"dark_gray\") or hex (\"#00BCD4\")\n\
             \n\
             {yaml}"
        )
    }
}

/// Resolved theme palette — `Color` values ready for rendering.
#[derive(Debug, Clone, Copy)]
pub struct ThemePalette {
    pub accent: Color,
    pub text: Color,
    pub thinking: Color,
    pub tool_result: Color,
    pub dim: Color,
    pub success: Color,
    pub warning: Color,
    pub danger: Color,
    pub surface: Color,
}

impl Default for ThemePalette {
    fn default() -> Self {
        Self::from_config(&ColorsConfig::default())
    }
}

impl ThemePalette {
    /// Build palette from config, falling back to defaults for invalid colors.
    pub fn from_config(cfg: &ColorsConfig) -> Self {
        let defaults = ColorsConfig::default();
        Self {
            accent: resolve_color(&cfg.accent, &defaults.accent),
            text: resolve_color(&cfg.text, &defaults.text),
            thinking: resolve_color(&cfg.thinking, &defaults.thinking),
            tool_result: resolve_color(&cfg.tool_result, &defaults.tool_result),
            dim: resolve_color(&cfg.dim, &defaults.dim),
            success: resolve_color(&cfg.success, &defaults.success),
            warning: resolve_color(&cfg.warning, &defaults.warning),
            danger: resolve_color(&cfg.danger, &defaults.danger),
            surface: resolve_color(&cfg.surface, &defaults.surface),
        }
    }
}

fn resolve_color(value: &str, fallback_str: &str) -> Color {
    parse_color(value).unwrap_or_else(|| {
        tracing::warn!("invalid color '{value}', falling back to '{fallback_str}'");
        parse_color(fallback_str).unwrap_or(Color::Reset)
    })
}

/// Get the config file path.
///
/// Returns `None` if the home directory cannot be determined (the caller
/// should fall back to defaults).
fn config_path() -> Option<PathBuf> {
    let home = if let Ok(env_home) = std::env::var("WING_HOME") {
        PathBuf::from(env_home)
    } else {
        dirs::home_dir()?.join(".wing")
    };
    Some(home.join("tui").join("config.yaml"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_palette() {
        let p = ThemePalette::default();
        assert_eq!(p.accent, Color::Cyan);
        assert_eq!(p.text, Color::White);
        assert_eq!(p.thinking, Color::Gray);
        assert_eq!(p.tool_result, Color::DarkGray);
        assert_eq!(p.dim, Color::DarkGray);
        assert_eq!(p.success, Color::Green);
        assert_eq!(p.warning, Color::Yellow);
        assert_eq!(p.danger, Color::Red);
        assert_eq!(p.surface, Color::Rgb(52, 53, 65));
    }

    #[test]
    fn test_custom_palette() {
        let cfg = ColorsConfig {
            accent: "#ff00ff".into(),
            dim: "gray".into(),
            ..ColorsConfig::default()
        };
        let p = ThemePalette::from_config(&cfg);
        assert_eq!(p.accent, Color::Rgb(255, 0, 255));
        assert_eq!(p.dim, Color::Gray);
        // Untouched defaults
        assert_eq!(p.text, Color::White);
    }

    #[test]
    fn test_invalid_color_fallback() {
        let cfg = ColorsConfig {
            accent: "neon_pink".into(),
            ..ColorsConfig::default()
        };
        let p = ThemePalette::from_config(&cfg);
        // Falls back to default "cyan"
        assert_eq!(p.accent, Color::Cyan);
    }

    #[test]
    fn test_default_config_yaml_roundtrip() {
        let cfg = AppConfig::default();
        let yaml = serde_yaml::to_string(&cfg).unwrap();
        let parsed: AppConfig = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(parsed.colors.accent, "cyan");
        assert_eq!(parsed.layout.max_input_lines, 10);
    }
}
