// Smoke bundler: `tools/smoke/main.ts` → `out/smoke/smoke.mjs`.
//
// Why a bundle at all: the smoke must run the *shipped* host code (TypeScript,
// aliased `vscode`, ESM source) as a plain `node` process. esbuild does exactly
// that in one step — no ts-node, no build of the extension bundle, and the
// `vscode` alias below is the only platform stub.
//
// `alias` (not `external`) is deliberate: the host layer really does import
// `vscode`, and the smoke supplies a poisoned stub so an accidental call fails
// loudly (`tools/smoke/vscode-stub.ts`).

import { mkdirSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import esbuild from 'esbuild';

const root = path.dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes('--watch');

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [path.join(root, 'tools/smoke/main.ts')],
  outfile: path.join(root, 'out/smoke/smoke.mjs'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: true,
  logLevel: 'info',
  alias: {
    vscode: path.join(root, 'tools/smoke/vscode-stub.ts'),
  },
  banner: {
    js: '// generated by esbuild.smoke.mjs — the wing vscode smoke. Do not edit.',
  },
};

mkdirSync(path.join(root, 'out/smoke'), { recursive: true });

if (watch) {
  const context = await esbuild.context(options);
  await context.watch();
  process.stdout.write('[esbuild] watching tools/smoke/main.ts → out/smoke/smoke.mjs\n');
} else {
  await esbuild.build(options);
}
