/**
 * The smoke's real gateway: locate the binary, boot an **isolated** instance,
 * wait for health, shut it down.
 *
 * Isolation is the hard requirement (the user's own gateway runs on 32523 against
 * `~/.wing`):
 *
 * - a temp `WING_HOME` + `WING_SESSIONS_PATH` under `os.tmpdir()`, injected into
 *   the child's environment — the smoke never reads or writes `~/.wing`;
 * - the port is an OS-assigned free one (`listen(0)` + close): the smoke refuses
 *   to run on the user's port even by accident (`assertIsolated` below);
 * - `autoStart: false` on the host side, so the launcher only ever *probes*;
 * - shutdown is `/api/shutdown` → SIGTERM → SIGKILL, always run in a `finally`.
 */

import { spawn } from 'node:child_process';
import type { ChildProcess } from 'node:child_process';
import { existsSync, mkdirSync, openSync, closeSync, readFileSync, writeFileSync } from 'node:fs';
import { createServer } from 'node:net';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import type { FakeProvider } from './fake-provider';

/** The user's live gateway port — never touch it. */
export const FORBIDDEN_PORT = 32_523;

export interface GatewayBinary {
  readonly path: string;
  /** Where it came from (for the report). */
  readonly source: string;
}

const here = path.dirname(fileURLToPath(import.meta.url));
/** `<repo>/extensions/vscode/tools/smoke` → `<repo>`. */
export const repoRoot = path.resolve(here, '..', '..', '..', '..');

/**
 * Resolve `wing-gateway`.
 *
 * Order: `$WING_GATEWAY_BIN` → the checkout's `.venv` → `PATH`. `null` means
 * "skip the smoke" (the caller turns that into exit code 3 with a readable
 * message) — never a hard failure, because not having the gateway installed is a
 * perfectly normal state for a front-end-only checkout.
 */
export function findGatewayBinary(env: NodeJS.ProcessEnv = process.env): GatewayBinary | null {
  const override = env['WING_GATEWAY_BIN'];
  if (override !== undefined && override !== '') {
    if (existsSync(override)) {
      return { path: override, source: '$WING_GATEWAY_BIN' };
    }
    throw new Error(`$WING_GATEWAY_BIN points at a missing file: ${override}`);
  }
  const candidates = [
    path.join(repoRoot, '.venv', 'bin', 'wing-gateway'),
    path.join(repoRoot, '.venv', 'Scripts', 'wing-gateway.exe'),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return { path: candidate, source: 'repository .venv' };
    }
  }
  for (const directory of (env['PATH'] ?? '').split(path.delimiter)) {
    if (directory === '') {
      continue;
    }
    const candidate = path.join(directory, 'wing-gateway');
    if (existsSync(candidate)) {
      return { path: candidate, source: 'PATH' };
    }
  }
  return null;
}

/** Pick a free port (bind(0), read, release). Small race window; acceptable. */
export async function freePort(): Promise<number> {
  const server = createServer();
  await new Promise<void>((resolve, reject) => {
    server.once('error', reject);
    server.listen(0, '127.0.0.1', resolve);
  });
  const address = server.address();
  const port = typeof address === 'object' && address !== null ? address.port : 0;
  await new Promise<void>((resolve) => {
    server.close(() => {
      resolve();
    });
  });
  if (port === FORBIDDEN_PORT) {
    throw new Error(`refusing to use the user's gateway port ${FORBIDDEN_PORT}`);
  }
  return port;
}

export function renderConfig(options: {
  readonly providerBaseUrl: string;
  readonly port: number;
  readonly model: string;
}): string {
  const systemPrompt = 'You are the wing smoke agent. Answer briefly and deterministically.';
  return [
    '# generated by the wing vscode smoke on every run — never edit, never keep',
    'providers:',
    '  - name: smoke',
    '    protocol: openai',
    `    base_url: ${options.providerBaseUrl}`,
    '    api_key: smoke-key',
    '    timeout_first_chunk: 30.0',
    '    timeout_total: 120.0',
    '    max_retries: 0',
    '    max_retry_delay: 1.0',
    '    explicit_cache_mode: true',
    '    extra_body: {}',
    'agents:',
    '  - name: default',
    `    model: ${options.model}`,
    '    provider: smoke',
    '    default: true',
    `    system_prompt: ${JSON.stringify(systemPrompt)}`,
    '    tools:',
    '      - Bash',
    '      - Read',
    '      - Write',
    '      - Edit',
    '      - Glob',
    '      - Grep',
    '      - AskUserQuestion',
    '      - TodoWrite',
    '    context_window_tokens: 200000',
    '    keep_recent_tokens: 50000',
    '    skills: []',
    '    rules: []',
    'hooks: []',
    '# Every Bash command is dangerous → the approval lane is reachable. The smoke',
    '# drives "y" and the yolo toggle explicitly.',
    'safe_command_patterns: []',
    'yolo: false',
    'log:',
    '  level: INFO',
    'gateway:',
    '  host: 127.0.0.1',
    `  port: ${options.port}`,
    '  auth:',
    '    enabled: false',
    'commands:',
    '  paths: []',
    '',
  ].join('\n');
}

export interface SmokeGatewayOptions {
  readonly binary: GatewayBinary;
  readonly provider: FakeProvider;
  readonly model: string;
  readonly root: string;
  readonly logFile: string;
}

export class SmokeGateway {
  readonly root: string;
  readonly wingHome: string;
  readonly sessionsPath: string;
  readonly workspace: string;
  readonly logFile: string;
  readonly model: string;

  private process: ChildProcess | null = null;
  private logFd: number | null = null;
  private readonly binary: GatewayBinary;
  private readonly provider: FakeProvider;
  private portValue = 0;

  constructor(options: SmokeGatewayOptions) {
    this.binary = options.binary;
    this.provider = options.provider;
    this.model = options.model;
    this.root = options.root;
    this.wingHome = path.join(options.root, 'wing_home');
    this.sessionsPath = path.join(options.root, 'sessions');
    this.workspace = path.join(options.root, 'workspace');
    this.logFile = options.logFile;
  }

  get port(): number {
    return this.portValue;
  }

  get baseUrl(): string {
    return `http://127.0.0.1:${this.portValue}`;
  }

  async start(): Promise<void> {
    mkdirSync(path.join(this.wingHome, 'core'), { recursive: true });
    mkdirSync(this.sessionsPath, { recursive: true });
    mkdirSync(this.workspace, { recursive: true });
    const forced = Number(process.env['WING_SMOKE_GATEWAY_PORT'] ?? Number.NaN);
    this.portValue = Number.isInteger(forced) && forced > 0 ? forced : await freePort();
    assertIsolated(this.portValue);
    writeFileSync(
      path.join(this.wingHome, 'core', 'config.yaml'),
      renderConfig({ providerBaseUrl: this.provider.baseUrl, port: this.portValue, model: this.model }),
      'utf8',
    );

    this.logFd = openSync(this.logFile, 'a');
    const child = spawn(this.binary.path, ['-p', String(this.portValue)], {
      cwd: this.root,
      env: {
        ...process.env,
        WING_HOME: this.wingHome,
        WING_SESSIONS_PATH: this.sessionsPath,
        PYTHONUNBUFFERED: '1',
      },
      stdio: ['ignore', this.logFd, this.logFd],
    });
    this.process = child;

    await this.waitForHealth(30_000);
  }

  private async waitForHealth(timeoutMs: number): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    for (;;) {
      const child = this.process;
      if (child === null) {
        throw new Error('gateway process is gone');
      }
      if (child.exitCode !== null || child.signalCode !== null) {
        throw new Error(
          `wing-gateway exited before becoming healthy (code=${child.exitCode}, signal=${child.signalCode})\n` +
            this.logTail(),
        );
      }
      try {
        const response = await fetch(`${this.baseUrl}/api/health`);
        if (response.ok) {
          const body = (await response.json()) as { service?: unknown };
          if (body.service !== 'wing-gateway') {
            throw new Error(`health answered but is not a wing gateway: ${JSON.stringify(body)}`);
          }
          return;
        }
      } catch {
        // not listening yet
      }
      if (Date.now() >= deadline) {
        throw new Error(`health check timed out after ${timeoutMs} ms\n${this.logTail()}`);
      }
      await new Promise<void>((resolve) => {
        setTimeout(resolve, 50);
      });
    }
  }

  logTail(lines = 40): string {
    try {
      const text = readFileSync(this.logFile, 'utf8');
      return `--- gateway.log tail (${this.logFile}) ---\n${text.split('\n').slice(-lines).join('\n')}`;
    } catch {
      return `--- gateway.log (${this.logFile}) unavailable ---`;
    }
  }

  /** `/api/shutdown` → wait → SIGTERM → SIGKILL. Idempotent, never throws. */
  async stop(): Promise<void> {
    const child = this.process;
    this.process = null;
    if (child !== null && child.exitCode === null) {
      try {
        await fetch(`${this.baseUrl}/api/shutdown`, { method: 'POST', body: '{}' });
      } catch {
        // already gone
      }
      const exited = await waitForExit(child, 5_000);
      if (!exited) {
        child.kill('SIGTERM');
        const terminated = await waitForExit(child, 5_000);
        if (!terminated) {
          child.kill('SIGKILL');
          await waitForExit(child, 5_000);
        }
      }
    }
    if (this.logFd !== null) {
      closeSync(this.logFd);
      this.logFd = null;
    }
  }
}

/** Belt and braces: the smoke must never talk to the user's live gateway. */
export function assertIsolated(port: number): void {
  if (port === FORBIDDEN_PORT) {
    throw new Error(
      `the smoke refuses to use port ${FORBIDDEN_PORT}: that is the user's live gateway. ` +
        'Isolate the run (temp WING_HOME + an OS-assigned port).',
    );
  }
}

function waitForExit(child: ChildProcess, timeoutMs: number): Promise<boolean> {
  if (child.exitCode !== null || child.signalCode !== null) {
    return Promise.resolve(true);
  }
  return new Promise<boolean>((resolve) => {
    const timer = setTimeout(() => {
      resolve(false);
    }, timeoutMs);
    child.once('exit', () => {
      clearTimeout(timer);
      resolve(true);
    });
  });
}

/** Where the smoke keeps its scratch state (overridable for debugging). */
export function smokeRoot(): string {
  const override = process.env['WING_SMOKE_ROOT'];
  const root =
    override !== undefined && override !== '' ? override : path.join(os.tmpdir(), 'wing-vscode-smoke');
  mkdirSync(root, { recursive: true });
  return root;
}
