"""ProbeEnv 的配置生成与端口/健康等待逻辑单测（tasks 2.4）。

纯单测：不起网关进程。健康轮询用测试内自建的 aiohttp 小应用验证
（假 Provider 同款栈，不是产品网关）。
"""

import socket
from pathlib import Path
from typing import Any, cast

import pytest
import yaml
from aiohttp import web

from wing_probe.env import (
    DEFAULT_AGENT_TOOLS,
    DEFAULT_CONTEXT_WINDOW_TOKENS,
    DEFAULT_KEEP_RECENT_TOKENS,
    DEFAULT_SYSTEM_PROMPT,
    DEFAULT_PROBE_MODEL,
    LOOPBACK_HOSTS,
    ProbeEnv,
    ProbeEnvError,
    log_section,
    merge_no_proxy,
    model_declaration_id,
    model_declaration_name,
    read_log_tail,
    render_config_yaml,
    repo_root,
    reserve_port,
    resolve_gateway_bin,
    resolve_model_declarations,
    wait_for_health,
    write_config,
)


def test_render_config_points_provider_at_fake() -> None:
    text = render_config_yaml(
        provider_base_url="http://127.0.0.1:45123/v1", gateway_port=45124
    )
    config = yaml.safe_load(text)

    provider = config["providers"][0]
    assert provider["protocol"] == "openai"
    assert provider["base_url"] == "http://127.0.0.1:45123/v1"
    assert provider["api_key"] == "probe-key"
    # 重试有界且可数：语义重试场景需要它 >0（一次逻辑调用 ≈ 1+max_retries 次消费）
    assert provider["max_retries"] == 2
    assert provider["max_retry_delay"] == 1.0
    # models 是目录的唯一来源（远端发现退役）：缺省只声明模板 model 自己。
    assert provider["models"] == [DEFAULT_PROBE_MODEL]

    agent = config["agents"][0]
    assert agent["name"] == "default"
    assert agent["default"] is True
    assert agent["model"] == DEFAULT_PROBE_MODEL
    # agents[].provider 已从配置契约里删除：probe 不再生成它。
    assert "provider" not in agent
    # system prompt 非空：system 段要真的进请求（"system + 摘要/前缀"断言的前提）
    assert agent["system_prompt"] == DEFAULT_SYSTEM_PROMPT
    assert agent["system_prompt"].strip()
    assert tuple(agent["tools"]) == DEFAULT_AGENT_TOOLS
    assert agent["skills"] == [] and agent["rules"] == []

    assert config["gateway"]["port"] == 45124
    assert config["gateway"]["auth"]["enabled"] is False
    assert config["yolo"] is False
    assert text.startswith("# generated by wing-probe")


def test_render_config_hooks_section() -> None:
    """hooks 段：默认空（不加载 hook）；显式传入时原样落进 config.yaml。"""
    default = yaml.safe_load(
        render_config_yaml(provider_base_url="http://127.0.0.1:1/v1", gateway_port=2)
    )
    assert default["hooks"] == []

    configured = yaml.safe_load(
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            hooks=["hooks/*.py", "~/.wing/hooks/*.py"],
        )
    )
    assert configured["hooks"] == ["hooks/*.py", "~/.wing/hooks/*.py"]


def test_render_config_base_url_without_trailing_slash() -> None:
    text = render_config_yaml(
        provider_base_url="http://127.0.0.1:1/v1/", gateway_port=2
    )
    assert yaml.safe_load(text)["providers"][0]["base_url"] == "http://127.0.0.1:1/v1"


def test_render_config_overrides() -> None:
    config = yaml.safe_load(
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            model="probe/thing",
            tools=["Bash"],
            system_prompt="be terse",
            context_window_tokens=1000,
            keep_recent_tokens=100,
        )
    )
    assert config["agents"][0]["model"] == "probe/thing"
    assert config["agents"][0]["tools"] == ["Bash"]
    assert config["agents"][0]["system_prompt"] == "be terse"
    assert config["agents"][0]["context_window_tokens"] == 1000
    assert config["agents"][0]["keep_recent_tokens"] == 100


def test_write_config_creates_core_layout(tmp_path: Path) -> None:
    path = write_config(tmp_path / "wing_home", "providers: []\n")
    assert path == tmp_path / "wing_home" / "core" / "config.yaml"
    assert path.read_text(encoding="utf-8") == "providers: []\n"


def test_reserve_port_returns_bindable_port() -> None:
    port = reserve_port()
    assert 1024 < port < 65536
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", port))  # 预留后立即释放：还能再绑


def test_env_layout_is_under_root(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path, health_timeout=0.5)
    assert env.wing_home == tmp_path.resolve() / "wing_home"
    assert env.sessions_path == tmp_path.resolve() / "sessions"
    assert env.artifacts_path == tmp_path.resolve() / "artifacts"
    assert env.config_path == env.wing_home / "core" / "config.yaml"
    assert env.log_path == tmp_path.resolve() / "gateway.log"
    assert env.session_dir("abc") == env.sessions_path / "abc"

    env_vars = env.env_vars()
    assert env_vars["WING_HOME"] == str(env.wing_home)
    assert env_vars["WING_SESSIONS_PATH"] == str(env.sessions_path)
    assert env_vars["PATH"]  # 继承外部环境


def test_env_vars_override(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path, env_overrides={"WING_HOME": "/elsewhere"})
    assert env.env_vars()["WING_HOME"] == "/elsewhere"


def test_env_unstarted_attrs_and_idempotent_stop(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path)
    assert env.port is None
    assert env.gateway_bin is None
    assert env.process is None
    assert env.gateway_url == "http://127.0.0.1:0"
    assert env.provider_url.startswith("http://127.0.0.1:")
    assert env.command()[-2:] == ["-p", "0"]
    assert isinstance(env.started_at, float)
    assert env.provider.started is False


def test_log_tail_reads_gateway_log(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path)
    tmp_path.mkdir(parents=True, exist_ok=True)
    env.log_path.write_text("line 1\nline 2\nline 3\n", encoding="utf-8")
    assert env.log_tail(max_lines=2) == "line 2\nline 3"


@pytest.mark.asyncio
async def test_stop_is_idempotent_without_start(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path)
    await env.stop()
    await env.stop()  # 第二次是 no-op，不抛
    assert env.process is None


# ── 网关二进制解析 ──────────────────────────────────────────────


def test_resolve_gateway_bin_prefers_env_override(tmp_path: Path) -> None:
    fake = tmp_path / "wing-gateway"
    fake.write_text("#!/bin/sh\n")
    resolved = resolve_gateway_bin(env={"WING_GATEWAY_BIN": str(fake)})
    assert resolved == fake.resolve()


def test_resolve_gateway_bin_reports_missing_override(tmp_path: Path) -> None:
    missing = tmp_path / "nope"
    with pytest.raises(ProbeEnvError, match="missing file"):
        resolve_gateway_bin(env={"WING_GATEWAY_BIN": str(missing)})


def test_resolve_gateway_bin_next_to_python(tmp_path: Path) -> None:
    binary = tmp_path / "bin" / "wing-gateway"
    binary.parent.mkdir()
    binary.write_text("#!/bin/sh\n")
    resolved = resolve_gateway_bin(env={}, executable=str(tmp_path / "bin" / "python"))
    assert resolved == binary.resolve()


def test_resolve_gateway_bin_repo_venv(tmp_path: Path) -> None:
    binary = tmp_path / ".venv" / "bin" / "wing-gateway"
    binary.parent.mkdir(parents=True)
    binary.write_text("#!/bin/sh\n")
    resolved = resolve_gateway_bin(
        env={}, executable=str(tmp_path / "elsewhere" / "python"), root=tmp_path
    )
    assert resolved == binary.resolve()


def test_resolve_gateway_bin_falls_back_to_path(tmp_path: Path) -> None:
    binary = tmp_path / "wing-gateway"
    binary.write_text("#!/bin/sh\n")
    resolved = resolve_gateway_bin(
        env={},
        executable="/nonexistent/python",
        root=tmp_path / "no-checkout",
        which=lambda _: str(binary),
    )
    assert resolved == binary.resolve()


def test_resolve_gateway_bin_error_mentions_uv_sync(tmp_path: Path) -> None:
    with pytest.raises(ProbeEnvError) as excinfo:
        resolve_gateway_bin(
            env={},
            executable=str(tmp_path / "python"),
            root=tmp_path / "no-checkout",
            which=lambda _: None,
        )
    message = str(excinfo.value)
    assert "wing-gateway executable not found" in message
    assert "uv sync" in message


def test_repo_root_found_in_checkout() -> None:
    root = repo_root()
    assert root is not None
    assert (root / "libs" / "core" / "pyproject.toml").is_file()


# ── 日志尾部 ────────────────────────────────────────────────────


def test_read_log_tail(tmp_path: Path) -> None:
    path = tmp_path / "gateway.log"
    path.write_text("\n".join(f"line {i}" for i in range(100)), encoding="utf-8")
    tail = read_log_tail(path, max_lines=5)
    assert tail.splitlines() == [f"line {i}" for i in range(95, 100)]
    assert read_log_tail(tmp_path / "missing.log").startswith("(cannot read")
    assert read_log_tail(None) == "(no log file)"

    truncated = read_log_tail(path, max_lines=100, max_chars=20)
    assert truncated.startswith("…")
    assert len(truncated) == 21

    section = log_section(path, title="gateway.log tail")
    assert section.startswith(f"--- gateway.log tail ({path}) ---")


# ── 健康等待 ────────────────────────────────────────────────────


async def _start_health_app(status: int) -> tuple[web.AppRunner, int]:
    app = web.Application()

    async def handler(request: web.Request) -> web.Response:
        return web.Response(status=status, text="ok" if status == 200 else "nope")

    app.router.add_get("/api/health", handler)
    runner = web.AppRunner(app, access_log=None)
    await runner.setup()
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(("127.0.0.1", 0))
    sock.listen(8)
    sock.setblocking(False)
    port = int(sock.getsockname()[1])
    await web.SockSite(runner, sock).start()
    return runner, port


@pytest.mark.asyncio
async def test_wait_for_health_returns_when_ready() -> None:
    runner, port = await _start_health_app(200)
    try:
        await wait_for_health(
            f"http://127.0.0.1:{port}/api/health", timeout=5.0, interval=0.01
        )
    finally:
        await runner.cleanup()


@pytest.mark.asyncio
async def test_wait_for_health_times_out_with_log_tail(tmp_path: Path) -> None:
    runner, port = await _start_health_app(500)
    log = tmp_path / "gateway.log"
    log.write_text("ERROR: something went wrong\n", encoding="utf-8")
    try:
        with pytest.raises(ProbeEnvError) as excinfo:
            await wait_for_health(
                f"http://127.0.0.1:{port}/api/health",
                timeout=0.3,
                interval=0.05,
                log_path=log,
            )
    finally:
        await runner.cleanup()
    message = str(excinfo.value)
    assert "health check timed out after 0.3s" in message
    assert "last status: 500" in message
    assert "ERROR: something went wrong" in message


@pytest.mark.asyncio
async def test_wait_for_health_reports_dead_process(tmp_path: Path) -> None:
    class DeadProcess:
        returncode = 3

        def poll(self) -> int:
            return 3

    log = tmp_path / "gateway.log"
    log.write_text("address already in use\n", encoding="utf-8")
    dead_process = cast(Any, DeadProcess())
    with pytest.raises(ProbeEnvError) as excinfo:
        await wait_for_health(
            "http://127.0.0.1:1/api/health",
            timeout=5.0,
            interval=0.01,
            process=dead_process,
            log_path=log,
        )
    message = str(excinfo.value)
    assert "exited with code 3" in message
    assert "address already in use" in message


@pytest.mark.asyncio
async def test_wait_for_health_reports_unreachable_url(tmp_path: Path) -> None:
    # 关闭的端口：连接被拒 → 报 no response
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.bind(("127.0.0.1", 0))
        port = int(probe.getsockname()[1])
    with pytest.raises(ProbeEnvError, match="no response"):
        await wait_for_health(
            f"http://127.0.0.1:{port}/api/health", timeout=0.2, interval=0.05
        )


# ── 模型声明与 images 段（阶段 2：model declaration） ──────────────


def test_render_config_defaults_models_to_template_model() -> None:
    """缺省写 ``[model]``（模板 model 必须落在 id 空间）；images 仍不写。"""
    config = yaml.safe_load(
        render_config_yaml(provider_base_url="http://127.0.0.1:1/v1", gateway_port=2)
    )
    assert config["providers"][0]["models"] == [DEFAULT_PROBE_MODEL]
    assert "images" not in config


def test_render_config_model_declarations() -> None:
    """models 原样写进 providers[0].models（元素 str 或 dict）+ 追加模板 model。"""
    declarations: list[Any] = [
        "legacy-model",
        {
            "name": "probe/vision",
            "display_name": "Vision",
            "description": "sees images",
            "capabilities": {"vision": True},
        },
    ]
    config = yaml.safe_load(
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            models=declarations,
        )
    )
    # 模板 model（probe/default）不在声明里 → 追加，否则 agents[].model 解析不了。
    assert config["providers"][0]["models"] == [*declarations, DEFAULT_PROBE_MODEL]


def test_resolve_model_declarations_rules() -> None:
    """组合规则：None = [model]；已在 id 空间不追加；撞调用名时不追加（不制造重名）。"""
    # None → 只声明模板 model（id = name）。
    assert resolve_model_declarations(model="probe/default", models=None) == [
        "probe/default"
    ]
    # 已在 effective id 集合里（显式 id 形态）→ 原样，不追加。
    declared: list[Any] = [{"id": "probe/default", "name": "upstream-default"}]
    assert (
        resolve_model_declarations(model="probe/default", models=declared) == declared
    )
    # 已在调用名集合里（id 是别的）→ 不追加：追加会撞 duplicate model name，
    # 报错比真实问题更误导（网关会以 unknown model id 明说模板 model 不在 id 空间）。
    shared: list[Any] = [{"id": "other", "name": "probe/default"}]
    assert resolve_model_declarations(model="probe/default", models=shared) == shared
    # 都不在 → 追加。
    others: list[Any] = ["probe/one"]
    assert resolve_model_declarations(model="probe/default", models=others) == [
        "probe/one",
        "probe/default",
    ]


def test_model_declaration_helpers() -> None:
    """effective id / 调用名的两形态口径（str 与 dict 混排）。"""
    assert model_declaration_id("plain") == "plain"
    assert model_declaration_id({"name": "upstream"}) == "upstream"
    assert model_declaration_id({"id": "alias", "name": "upstream"}) == "alias"
    assert model_declaration_name("plain") == "plain"
    assert model_declaration_name({"id": "alias", "name": "upstream"}) == "upstream"
    with pytest.raises(ProbeEnvError, match="needs a non-empty name"):
        model_declaration_id({"display_name": "no name"})


def test_render_config_extra_providers() -> None:
    """附加 provider 与主 provider 逐字段同形（同一份默认块），models 必填非空。"""
    config = yaml.safe_load(
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            models=["probe/one"],
            extra_providers=[
                {
                    "name": "probe2",
                    "base_url": "http://127.0.0.1:1/probe2/v1/",
                    "models": [{"id": "p2-shared", "name": "shared"}],
                }
            ],
        )
    )
    primary, extra = config["providers"]
    assert extra["name"] == "probe2"
    assert extra["base_url"] == "http://127.0.0.1:1/probe2/v1"
    assert extra["models"] == [{"id": "p2-shared", "name": "shared"}]
    # 接线键与主 provider 同源（同一个 _default_provider_block）。
    for key in ("protocol", "api_key", "max_retries", "max_retry_delay"):
        assert extra[key] == primary[key]
    # 模板 model 只追加到主 provider。
    assert primary["models"] == ["probe/one", DEFAULT_PROBE_MODEL]

    with pytest.raises(ProbeEnvError, match="declares no models"):
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            extra_providers=[{"name": "probe2", "base_url": "x", "models": []}],
        )
    with pytest.raises(ProbeEnvError, match="needs a name"):
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            extra_providers=[{"models": ["probe/one"]}],
        )


def test_render_config_images_section() -> None:
    """images 原样写进顶层 images: 段。"""
    config = yaml.safe_load(
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            images={"max_images": 2, "count_quantum": 1, "request_budget_bytes": 1024},
        )
    )
    assert config["images"] == {
        "max_images": 2,
        "count_quantum": 1,
        "request_budget_bytes": 1024,
    }


def test_env_render_config_passes_models_and_images(tmp_path: Path) -> None:
    """ProbeEnv 的 models / images 参数进入生成的配置文本（probe_env 标记透传的落点）。"""
    env = ProbeEnv(
        tmp_path,
        models=["legacy", {"name": "probe/vision", "capabilities": {"vision": True}}],
        images={"max_images": 4},
    )
    config = yaml.safe_load(env._render_config(45124))
    assert config["gateway"]["port"] == 45124
    assert config["providers"][0]["models"] == [
        "legacy",
        {"name": "probe/vision", "capabilities": {"vision": True}},
        DEFAULT_PROBE_MODEL,  # 模板 model 不在声明里 → 追加（否则网关起不来）
    ]
    assert config["images"] == {"max_images": 4}


def test_env_extra_providers_point_at_fake_provider_prefix(tmp_path: Path) -> None:
    """ProbeEnv 的附加 provider 指到假 Provider 的第二条路径前缀（跨 provider 场景）。"""
    env = ProbeEnv(
        tmp_path,
        models=["probe/one"],
        extra_providers=[{"name": "probe2", "models": ["probe/two"]}],
    )
    assert env._extra_provider_names() == ("probe2",)
    assert env.extra_provider_specs() == [
        {
            "name": "probe2",
            "base_url": f"{env.provider.url}/probe2/v1",
            "models": ["probe/two"],
        }
    ]
    config = yaml.safe_load(env._render_config(45124))
    assert [item["name"] for item in config["providers"]] == ["probe", "probe2"]
    assert config["providers"][1]["base_url"] == f"{env.provider.url}/probe2/v1"

    with pytest.raises(ProbeEnvError, match="needs a name"):
        ProbeEnv(tmp_path, extra_providers=[{"models": ["probe/two"]}])
    with pytest.raises(ProbeEnvError, match="declares no models"):
        env = ProbeEnv(tmp_path, extra_providers=[{"name": "probe2"}])
        env.extra_provider_specs()


def test_render_config_provider_extra_merges_into_provider() -> None:
    """provider_extra 的键值合进 providers[0]（provider 级透传旋钮）。"""
    baseline = yaml.safe_load(
        render_config_yaml(provider_base_url="http://127.0.0.1:1/v1", gateway_port=2)
    )
    configured = yaml.safe_load(
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            provider_extra={"image_delivery": "inline"},
        )
    )
    assert "image_delivery" not in baseline["providers"][0]
    assert configured["providers"][0]["image_delivery"] == "inline"
    # 合并只增不改：假 Provider 接线键原样保留。
    for key in ("protocol", "base_url", "api_key", "models"):
        assert configured["providers"][0].get(key) == baseline["providers"][0].get(key)


def test_env_render_config_passes_provider_extra(tmp_path: Path) -> None:
    """ProbeEnv 的 provider_extra 参数进入生成的配置文本（probe_env 标记透传的落点）。"""
    env = ProbeEnv(tmp_path, provider_extra={"image_delivery": "followup"})
    config = yaml.safe_load(env._render_config(45124))
    assert config["providers"][0]["image_delivery"] == "followup"


def test_render_config_auth_section() -> None:
    """auth 段：缺省仍是 ``{"enabled": False}``；给了原文时整体替换（不合并）。"""
    baseline = yaml.safe_load(
        render_config_yaml(provider_base_url="http://127.0.0.1:1/v1", gateway_port=2)
    )
    assert baseline["gateway"]["auth"] == {"enabled": False}

    configured = yaml.safe_load(
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            auth={
                "enabled": True,
                "keys": [
                    {"key": "probe-admin-key"},
                    {"key": "probe-tool-key", "role": "tool_runtime"},
                ],
            },
        )
    )
    assert configured["gateway"]["auth"] == {
        "enabled": True,
        "keys": [
            {"key": "probe-admin-key"},
            {"key": "probe-tool-key", "role": "tool_runtime"},
        ],
    }
    # 其余网关接线键不因 auth 而漂移（假 Provider 场景照常起得来）。
    assert configured["gateway"]["host"] == baseline["gateway"]["host"]
    assert configured["gateway"]["port"] == 2


def test_env_render_config_passes_auth(tmp_path: Path) -> None:
    """ProbeEnv 的 auth 参数进入生成的配置文本（probe_env 标记透传的落点）。"""
    env = ProbeEnv(tmp_path, auth={"enabled": True, "keys": [{"key": "k"}]})
    config = yaml.safe_load(env._render_config(45124))
    assert config["gateway"]["auth"] == {"enabled": True, "keys": [{"key": "k"}]}
    assert env.auth == {"enabled": True, "keys": [{"key": "k"}]}

    default_env = ProbeEnv(tmp_path)
    assert default_env.auth is None
    assert yaml.safe_load(default_env._render_config(1))["gateway"]["auth"] == {
        "enabled": False
    }


def test_shutdown_api_key_prefers_admin_role(tmp_path: Path) -> None:
    """关自己子进程用的 key：优先非 tool_runtime（默认角色 admin），只给
    tool_runtime 时退而用最后一把，没有 keys 则 None（关停走 terminate 兜底）。"""
    assert ProbeEnv(tmp_path).shutdown_api_key is None
    assert (
        ProbeEnv(tmp_path, auth={"enabled": True, "keys": []}).shutdown_api_key is None
    )
    assert (
        ProbeEnv(
            tmp_path,
            auth={"enabled": True, "keys": [{"key": "tool", "role": "tool_runtime"}]},
        ).shutdown_api_key
        == "tool"
    )
    assert (
        ProbeEnv(
            tmp_path,
            auth={
                "enabled": True,
                "keys": [
                    {"key": "tool", "role": "tool_runtime"},
                    {"key": "admin"},
                ],
            },
        ).shutdown_api_key
        == "admin"
    )


def test_merge_no_proxy_keeps_existing_and_adds_loopback() -> None:
    """NO_PROXY 合并：既有条目不丢、loopback 补齐、`*` 原样保留。"""
    default = ",".join(LOOPBACK_HOSTS)
    assert merge_no_proxy(None) == default
    assert merge_no_proxy("") == default
    assert merge_no_proxy("example.com") == f"example.com,{default}"
    assert merge_no_proxy("127.0.0.1") == default
    assert merge_no_proxy("*") == "*"
    # 多来源（NO_PROXY + no_proxy 两种拼写）取并集，重复不追加。
    assert merge_no_proxy("example.com", "corp.example.com") == (
        f"example.com,corp.example.com,{default}"
    )
    assert merge_no_proxy("example.com", "example.com") == f"example.com,{default}"
    assert merge_no_proxy(None, "corp.example.com") == f"corp.example.com,{default}"


def test_env_vars_keep_lowercase_no_proxy_entries(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """小写 `no_proxy` 的既有条目不得被覆写丢掉（只设小写拼写的那一半环境）。"""
    monkeypatch.delenv("NO_PROXY", raising=False)
    monkeypatch.setenv("no_proxy", "corp.example.com")
    env = ProbeEnv(tmp_path).env_vars()
    assert env["NO_PROXY"] == env["no_proxy"]
    assert "corp.example.com" in env["NO_PROXY"], env["NO_PROXY"]
    assert "127.0.0.1" in env["NO_PROXY"] and "localhost" in env["NO_PROXY"]


def test_env_vars_carry_loopback_no_proxy(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """网关子进程环境带 loopback NO_PROXY（子进程 httpx 也要绕开代理）。"""
    monkeypatch.delenv("NO_PROXY", raising=False)
    monkeypatch.delenv("no_proxy", raising=False)
    env = ProbeEnv(tmp_path).env_vars()
    assert "127.0.0.1" in env["NO_PROXY"] and "localhost" in env["NO_PROXY"]
    assert env["no_proxy"] == env["NO_PROXY"]


@pytest.mark.asyncio
async def test_wait_for_health_ignores_env_proxy(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """环境 / 系统代理不得劫持 loopback：health 检查直连本地应用（trust_env=False）。"""
    monkeypatch.setenv("HTTP_PROXY", "http://127.0.0.1:9")  # 死代理：走它必失败
    monkeypatch.setenv("http_proxy", "http://127.0.0.1:9")
    monkeypatch.setenv("ALL_PROXY", "http://127.0.0.1:9")
    runner, port = await _start_health_app(200)
    try:
        await wait_for_health(
            f"http://127.0.0.1:{port}/api/health", timeout=5.0, interval=0.01
        )
    finally:
        await runner.cleanup()


def test_env_render_config_passes_context_window_knobs(tmp_path: Path) -> None:
    """ProbeEnv 的上下文窗口旋钮进入 agent 配置（自动压缩场景的阈值来源）。

    默认与 ``render_config_yaml`` 的缺省一致（不因新增参数而漂移）；显式压小
    之后 ``compact_window = window - keep_recent`` 才是场景能算出来的数。
    """
    default = yaml.safe_load(ProbeEnv(tmp_path)._render_config(45124))["agents"][0]
    assert default["context_window_tokens"] == DEFAULT_CONTEXT_WINDOW_TOKENS
    assert default["keep_recent_tokens"] == DEFAULT_KEEP_RECENT_TOKENS

    env = ProbeEnv(tmp_path, context_window_tokens=1000, keep_recent_tokens=400)
    agent = yaml.safe_load(env._render_config(45124))["agents"][0]
    assert agent["context_window_tokens"] == 1000
    assert agent["keep_recent_tokens"] == 400


@pytest.mark.asyncio
async def test_restart_gateway_refuses_stopped_env(tmp_path: Path) -> None:
    """重启是"活环境"的操作：已 stop 的实例直接报错（单向闸门不破）。"""
    env = ProbeEnv(tmp_path)
    await env.stop()

    with pytest.raises(ProbeEnvError, match="one-way gate"):
        await env.restart_gateway()
    assert env.process is None


@pytest.mark.asyncio
async def test_restart_gateway_without_running_process_starts_one(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """未起进程时重启 = 起一个新的（不重复起第二个）。"""
    env = ProbeEnv(tmp_path)
    started: list[int] = []

    async def fake_start() -> None:
        started.append(1)

    monkeypatch.setattr(env, "start_gateway", fake_start)
    await env.restart_gateway()

    assert started == [1], "重启只调用一次 start_gateway"
    assert env.process is None
