"""ProbeEnv 的配置生成与端口/健康等待逻辑单测（tasks 2.4）。

纯单测：不起网关进程。健康轮询用测试内自建的 aiohttp 小应用验证
（假 Provider 同款栈，不是产品网关）。
"""

import socket
from pathlib import Path
from typing import Any, cast

import pytest
import yaml
from aiohttp import web

from wing_probe.env import (
    DEFAULT_AGENT_TOOLS,
    DEFAULT_SYSTEM_PROMPT,
    DEFAULT_PROBE_MODEL,
    ProbeEnv,
    ProbeEnvError,
    log_section,
    read_log_tail,
    render_config_yaml,
    repo_root,
    reserve_port,
    resolve_gateway_bin,
    wait_for_health,
    write_config,
)


def test_render_config_points_provider_at_fake() -> None:
    text = render_config_yaml(
        provider_base_url="http://127.0.0.1:45123/v1", gateway_port=45124
    )
    config = yaml.safe_load(text)

    provider = config["providers"][0]
    assert provider["protocol"] == "openai"
    assert provider["base_url"] == "http://127.0.0.1:45123/v1"
    assert provider["api_key"] == "probe-key"
    # 重试 / 退避不进首批：一次请求 = 一次剧本消费
    assert provider["max_retries"] == 0

    agent = config["agents"][0]
    assert agent["name"] == "default"
    assert agent["default"] is True
    assert agent["model"] == DEFAULT_PROBE_MODEL
    assert agent["provider"] == provider["name"]
    # system prompt 非空：system 段要真的进请求（"system + 摘要/前缀"断言的前提）
    assert agent["system_prompt"] == DEFAULT_SYSTEM_PROMPT
    assert agent["system_prompt"].strip()
    assert tuple(agent["tools"]) == DEFAULT_AGENT_TOOLS
    assert agent["skills"] == [] and agent["rules"] == []

    assert config["gateway"]["port"] == 45124
    assert config["gateway"]["auth"]["enabled"] is False
    assert config["yolo"] is False
    assert text.startswith("# generated by wing-probe")


def test_render_config_base_url_without_trailing_slash() -> None:
    text = render_config_yaml(
        provider_base_url="http://127.0.0.1:1/v1/", gateway_port=2
    )
    assert yaml.safe_load(text)["providers"][0]["base_url"] == "http://127.0.0.1:1/v1"


def test_render_config_overrides() -> None:
    config = yaml.safe_load(
        render_config_yaml(
            provider_base_url="http://127.0.0.1:1/v1",
            gateway_port=2,
            model="probe/thing",
            tools=["Bash"],
            system_prompt="be terse",
            context_window_tokens=1000,
            keep_recent_tokens=100,
        )
    )
    assert config["agents"][0]["model"] == "probe/thing"
    assert config["agents"][0]["tools"] == ["Bash"]
    assert config["agents"][0]["system_prompt"] == "be terse"
    assert config["agents"][0]["context_window_tokens"] == 1000
    assert config["agents"][0]["keep_recent_tokens"] == 100


def test_write_config_creates_core_layout(tmp_path: Path) -> None:
    path = write_config(tmp_path / "wing_home", "providers: []\n")
    assert path == tmp_path / "wing_home" / "core" / "config.yaml"
    assert path.read_text(encoding="utf-8") == "providers: []\n"


def test_reserve_port_returns_bindable_port() -> None:
    port = reserve_port()
    assert 1024 < port < 65536
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", port))  # 预留后立即释放：还能再绑


def test_env_layout_is_under_root(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path, health_timeout=0.5)
    assert env.wing_home == tmp_path.resolve() / "wing_home"
    assert env.sessions_path == tmp_path.resolve() / "sessions"
    assert env.artifacts_path == tmp_path.resolve() / "artifacts"
    assert env.config_path == env.wing_home / "core" / "config.yaml"
    assert env.log_path == tmp_path.resolve() / "gateway.log"
    assert env.session_dir("abc") == env.sessions_path / "abc"

    env_vars = env.env_vars()
    assert env_vars["WING_HOME"] == str(env.wing_home)
    assert env_vars["WING_SESSIONS_PATH"] == str(env.sessions_path)
    assert env_vars["PATH"]  # 继承外部环境


def test_env_vars_override(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path, env_overrides={"WING_HOME": "/elsewhere"})
    assert env.env_vars()["WING_HOME"] == "/elsewhere"


def test_env_unstarted_attrs_and_idempotent_stop(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path)
    assert env.port is None
    assert env.gateway_bin is None
    assert env.process is None
    assert env.gateway_url == "http://127.0.0.1:0"
    assert env.provider_url.startswith("http://127.0.0.1:")
    assert env.command()[-2:] == ["-p", "0"]
    assert isinstance(env.started_at, float)
    assert env.provider.started is False


def test_log_tail_reads_gateway_log(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path)
    tmp_path.mkdir(parents=True, exist_ok=True)
    env.log_path.write_text("line 1\nline 2\nline 3\n", encoding="utf-8")
    assert env.log_tail(max_lines=2) == "line 2\nline 3"


@pytest.mark.asyncio
async def test_stop_is_idempotent_without_start(tmp_path: Path) -> None:
    env = ProbeEnv(tmp_path)
    await env.stop()
    await env.stop()  # 第二次是 no-op，不抛
    assert env.process is None


# ── 网关二进制解析 ──────────────────────────────────────────────


def test_resolve_gateway_bin_prefers_env_override(tmp_path: Path) -> None:
    fake = tmp_path / "wing-gateway"
    fake.write_text("#!/bin/sh\n")
    resolved = resolve_gateway_bin(env={"WING_GATEWAY_BIN": str(fake)})
    assert resolved == fake.resolve()


def test_resolve_gateway_bin_reports_missing_override(tmp_path: Path) -> None:
    missing = tmp_path / "nope"
    with pytest.raises(ProbeEnvError, match="missing file"):
        resolve_gateway_bin(env={"WING_GATEWAY_BIN": str(missing)})


def test_resolve_gateway_bin_next_to_python(tmp_path: Path) -> None:
    binary = tmp_path / "bin" / "wing-gateway"
    binary.parent.mkdir()
    binary.write_text("#!/bin/sh\n")
    resolved = resolve_gateway_bin(env={}, executable=str(tmp_path / "bin" / "python"))
    assert resolved == binary.resolve()


def test_resolve_gateway_bin_repo_venv(tmp_path: Path) -> None:
    binary = tmp_path / ".venv" / "bin" / "wing-gateway"
    binary.parent.mkdir(parents=True)
    binary.write_text("#!/bin/sh\n")
    resolved = resolve_gateway_bin(
        env={}, executable=str(tmp_path / "elsewhere" / "python"), root=tmp_path
    )
    assert resolved == binary.resolve()


def test_resolve_gateway_bin_falls_back_to_path(tmp_path: Path) -> None:
    binary = tmp_path / "wing-gateway"
    binary.write_text("#!/bin/sh\n")
    resolved = resolve_gateway_bin(
        env={},
        executable="/nonexistent/python",
        root=tmp_path / "no-checkout",
        which=lambda _: str(binary),
    )
    assert resolved == binary.resolve()


def test_resolve_gateway_bin_error_mentions_uv_sync(tmp_path: Path) -> None:
    with pytest.raises(ProbeEnvError) as excinfo:
        resolve_gateway_bin(
            env={},
            executable=str(tmp_path / "python"),
            root=tmp_path / "no-checkout",
            which=lambda _: None,
        )
    message = str(excinfo.value)
    assert "wing-gateway executable not found" in message
    assert "uv sync" in message


def test_repo_root_found_in_checkout() -> None:
    root = repo_root()
    assert root is not None
    assert (root / "libs" / "core" / "pyproject.toml").is_file()


# ── 日志尾部 ────────────────────────────────────────────────────


def test_read_log_tail(tmp_path: Path) -> None:
    path = tmp_path / "gateway.log"
    path.write_text("\n".join(f"line {i}" for i in range(100)), encoding="utf-8")
    tail = read_log_tail(path, max_lines=5)
    assert tail.splitlines() == [f"line {i}" for i in range(95, 100)]
    assert read_log_tail(tmp_path / "missing.log").startswith("(cannot read")
    assert read_log_tail(None) == "(no log file)"

    truncated = read_log_tail(path, max_lines=100, max_chars=20)
    assert truncated.startswith("…")
    assert len(truncated) == 21

    section = log_section(path, title="gateway.log tail")
    assert section.startswith(f"--- gateway.log tail ({path}) ---")


# ── 健康等待 ────────────────────────────────────────────────────


async def _start_health_app(status: int) -> tuple[web.AppRunner, int]:
    app = web.Application()

    async def handler(request: web.Request) -> web.Response:
        return web.Response(status=status, text="ok" if status == 200 else "nope")

    app.router.add_get("/api/health", handler)
    runner = web.AppRunner(app, access_log=None)
    await runner.setup()
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(("127.0.0.1", 0))
    sock.listen(8)
    sock.setblocking(False)
    port = int(sock.getsockname()[1])
    await web.SockSite(runner, sock).start()
    return runner, port


@pytest.mark.asyncio
async def test_wait_for_health_returns_when_ready() -> None:
    runner, port = await _start_health_app(200)
    try:
        await wait_for_health(
            f"http://127.0.0.1:{port}/api/health", timeout=5.0, interval=0.01
        )
    finally:
        await runner.cleanup()


@pytest.mark.asyncio
async def test_wait_for_health_times_out_with_log_tail(tmp_path: Path) -> None:
    runner, port = await _start_health_app(500)
    log = tmp_path / "gateway.log"
    log.write_text("ERROR: something went wrong\n", encoding="utf-8")
    try:
        with pytest.raises(ProbeEnvError) as excinfo:
            await wait_for_health(
                f"http://127.0.0.1:{port}/api/health",
                timeout=0.3,
                interval=0.05,
                log_path=log,
            )
    finally:
        await runner.cleanup()
    message = str(excinfo.value)
    assert "health check timed out after 0.3s" in message
    assert "last status: 500" in message
    assert "ERROR: something went wrong" in message


@pytest.mark.asyncio
async def test_wait_for_health_reports_dead_process(tmp_path: Path) -> None:
    class DeadProcess:
        returncode = 3

        def poll(self) -> int:
            return 3

    log = tmp_path / "gateway.log"
    log.write_text("address already in use\n", encoding="utf-8")
    dead_process = cast(Any, DeadProcess())
    with pytest.raises(ProbeEnvError) as excinfo:
        await wait_for_health(
            "http://127.0.0.1:1/api/health",
            timeout=5.0,
            interval=0.01,
            process=dead_process,
            log_path=log,
        )
    message = str(excinfo.value)
    assert "exited with code 3" in message
    assert "address already in use" in message


@pytest.mark.asyncio
async def test_wait_for_health_reports_unreachable_url(tmp_path: Path) -> None:
    # 关闭的端口：连接被拒 → 报 no response
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.bind(("127.0.0.1", 0))
        port = int(probe.getsockname()[1])
    with pytest.raises(ProbeEnvError, match="no response"):
        await wait_for_health(
            f"http://127.0.0.1:{port}/api/health", timeout=0.2, interval=0.05
        )
