"""wing-probe —— 确定性集成测试基础设施。

三角色：假 Provider（锚定模型）、driver（假用户）、observer（断言）。场景侧
只需要 ``probe`` fixture 与 ``session.watch`` / ``session.history``：

    from wing_probe import Probe, Script, ToolCall, Turn

    probe.register("probe/basic", Turn.of(text="done"))
    session = await probe.session(model="probe/basic", yolo=True)
    await session.chat("hi")
    probe.files.assert_content("out.txt", equals="done\\n")
    probe.history(session).assert_chain_invariants()

本模块把四个子包的公共 API 收成单一出口（短路径即可用）：

- ``env``：``ProbeEnv`` 环境自举（临时 WING_HOME + 网关子进程 + 假 Provider）；
- ``probe``：``Probe`` 场景门面（会话工厂 / 视图 / 现场转储 / 逃生舱）；
- ``driver``：``Driver`` / ``Session``（HTTP + WS 公开协议驱动）与 ``HttpCall``；
- ``watch``：``Watcher`` 断言原语（expect / expect_none / assert_never /
  assert_ordered / events）与 ``ExpectationError``；
- ``history``：``HistoryView``（history.jsonl 独立解析）、三条内置不变量、
  三条红线过渡断言（compact / rewind / fork）、``fork_metadata``；
- ``files``：``FileAssertions``（workspace 文件断言）；
- ``provider``：剧本模型（``Script`` / ``Turn`` / ``ToolCall`` / ``Usage``）、
  ``FakeProvider``、``ContextView``（请求上下文断言）。

硬约束：本包不得 ``import wing``（门禁 ``wing_probe.guard`` 在每次测试运行强制）。

契约：``openspec/changes/wing-probe/design.md``（D1–D12）与
``specs/probe-harness/spec.md``。
"""

from wing_probe.driver import (
    CHUNK_TYPE,
    DEFAULT_MAX_SIZE,
    DEFAULT_TIMEOUT,
    DEFAULT_TURN_WITHIN,
    Driver,
    DriverError,
    DriverHttp,
    DriverHttpError,
    GatewayWS,
    HttpCall,
    Session,
    WsError,
    ws_url,
)
from wing_probe.env import (
    DEFAULT_AGENT_TOOLS,
    DEFAULT_PROBE_MODEL,
    ProbeEnv,
    ProbeEnvError,
    candidate_gateway_binaries,
    log_section,
    read_log_tail,
    render_config_yaml,
    repo_root,
    reserve_port,
    resolve_gateway_bin,
    wait_for_health,
    write_config,
)
from wing_probe.files import (
    ANY,
    FileAssertionError,
    FileAssertions,
    FileSnapshot,
)
from wing_probe.guard import (
    PKG_ROOT,
    Violation,
    check_tree,
    format_violations,
    is_forbidden,
    iter_python_files,
    scan_file,
    scan_source,
    scan_tree,
)
from wing_probe.history import (
    COMPACT_PREFIX,
    CURRENT_SENTINEL,
    DELTA_EVENT_TYPES,
    EVENT_ROLE,
    FORK_METADATA_FIELDS,
    FORK_SNAPSHOT_FIELDS,
    HISTORY_FILE,
    METADATA_FILE,
    MESSAGE_ROLES,
    REWIND_TO_ROOT_CONTENT,
    TRANSIENT_EVENT_TYPES,
    HistoryAssertionError,
    HistoryView,
    assert_chain_invariants,
    assert_compact_transition,
    assert_fork_of,
    assert_no_transient_records,
    assert_rewind_transition,
    assert_tool_pairing,
    describe_chain,
    fork_metadata,
    is_event,
    is_message,
    message_semantics,
    node_semantics,
    read_metadata,
    semantic_diff,
)
from wing_probe.probe import (
    INVARIANT_CHECKS,
    Probe,
    ProbeError,
    ProbeInvariantError,
    run_invariants,
)
from wing_probe.provider import (
    DONE_TEXT,
    SSE_CONTENT_TYPE,
    ContextAssertionError,
    ContextView,
    FakeProvider,
    LoggedRequest,
    MessageView,
    RequestLog,
    SSEFrame,
    Script,
    ScriptError,
    ScriptExhaustedError,
    ScriptRegistry,
    ToolCall,
    ToolCallView,
    Turn,
    UnregisteredModelError,
    Usage,
    chunk_payload,
    completion_response,
    encode_turn_stream,
    match_message,
    stream_frames,
)
from wing_probe.watch import (
    DEFAULT_WITHIN,
    Event,
    Expectation,
    ExpectationError,
    Frame,
    FrameLog,
    Timeline,
    Watcher,
    Where,
    render_frames,
    render_report,
    render_timeline,
)

__all__ = [
    "ANY",
    "CHUNK_TYPE",
    "COMPACT_PREFIX",
    "CURRENT_SENTINEL",
    "DEFAULT_AGENT_TOOLS",
    "DEFAULT_MAX_SIZE",
    "DEFAULT_PROBE_MODEL",
    "DEFAULT_TIMEOUT",
    "DEFAULT_TURN_WITHIN",
    "DEFAULT_WITHIN",
    "DELTA_EVENT_TYPES",
    "DONE_TEXT",
    "EVENT_ROLE",
    "FORK_METADATA_FIELDS",
    "FORK_SNAPSHOT_FIELDS",
    "HISTORY_FILE",
    "INVARIANT_CHECKS",
    "METADATA_FILE",
    "MESSAGE_ROLES",
    "PKG_ROOT",
    "REWIND_TO_ROOT_CONTENT",
    "SSE_CONTENT_TYPE",
    "TRANSIENT_EVENT_TYPES",
    "ContextAssertionError",
    "ContextView",
    "Driver",
    "DriverError",
    "DriverHttp",
    "DriverHttpError",
    "Event",
    "Expectation",
    "ExpectationError",
    "FakeProvider",
    "FileAssertionError",
    "FileAssertions",
    "FileSnapshot",
    "Frame",
    "FrameLog",
    "GatewayWS",
    "HistoryAssertionError",
    "HistoryView",
    "HttpCall",
    "LoggedRequest",
    "MessageView",
    "Probe",
    "ProbeEnv",
    "ProbeEnvError",
    "ProbeError",
    "ProbeInvariantError",
    "RequestLog",
    "SSEFrame",
    "Script",
    "ScriptError",
    "ScriptExhaustedError",
    "ScriptRegistry",
    "Session",
    "Timeline",
    "ToolCall",
    "ToolCallView",
    "Turn",
    "UnregisteredModelError",
    "Usage",
    "Violation",
    "Watcher",
    "Where",
    "WsError",
    "assert_chain_invariants",
    "assert_compact_transition",
    "assert_fork_of",
    "assert_no_transient_records",
    "assert_rewind_transition",
    "assert_tool_pairing",
    "candidate_gateway_binaries",
    "check_tree",
    "chunk_payload",
    "completion_response",
    "describe_chain",
    "encode_turn_stream",
    "fork_metadata",
    "format_violations",
    "is_event",
    "is_message",
    "is_forbidden",
    "iter_python_files",
    "log_section",
    "match_message",
    "message_semantics",
    "node_semantics",
    "read_log_tail",
    "read_metadata",
    "render_config_yaml",
    "render_frames",
    "render_report",
    "render_timeline",
    "repo_root",
    "reserve_port",
    "resolve_gateway_bin",
    "run_invariants",
    "scan_file",
    "scan_source",
    "scan_tree",
    "semantic_diff",
    "stream_frames",
    "wait_for_health",
    "write_config",
    "ws_url",
]
