/**
 * WingEvent mirror — the discriminated union of every event the gateway can push.
 *
 * Source of truth (Python):
 *   - `wing/event/base.py`      — WingEvent base, `error` / `notice` / `delivered`
 *   - `wing/event/react.py`     — react-loop events
 *   - `wing/event/state_change.py`
 *   - `wing/event/query_response.py`
 *   - the registry `EVENT_TYPES` in `wing/event/__init__.py`
 *
 * Wire rules the decoders rely on (`wire_dump`):
 *   - `target` / `parent_uuid` / `unzip_last_uuid` / `role` are stripped before
 *     sending; JSON `null` fields are stripped too, so "absent" always means
 *     "null" and the mirror normalises back to `| null` (never `undefined`).
 *   - `created_at` / `request_id` always exist (the backend generates them);
 *     they are read with an empty-string fallback so an old/hand-made payload
 *     still decodes (same rule as `WingEvent::from_history_value`).
 *
 * Decoding policy (the split matters — it is what keeps replay robust):
 *   - **Scalars are strict**: a required field that is missing or of the wrong
 *     JSON type makes the whole payload an {@link UnknownWingEvent}, never a
 *     typed event with holes in it.
 *   - **Collections of records are tolerant**: elements that do not decode are
 *     skipped (`sync_session` history / replay nodes, `ask.questions`,
 *     `content_blocks`, `branch_targets.targets`), mirroring the backend's own
 *     "skip nodes we do not understand" replay semantics.
 *   - **Unknown `type` is forward compatible**: it arrives as an
 *     {@link UnknownWingEvent} with the raw payload, never dropped.
 */

import {
  type JsonObject,
  ProtocolDecodeError,
  booleanOr,
  decodeEach,
  enumOr,
  isJsonObject,
  numberOr,
  optJsonObject,
  optNumber,
  optString,
  readJsonArray,
  readStringArray,
  reqBoolean,
  reqJsonArray,
  reqNumber,
  reqString,
  stringOr,
} from './json';
import {
  type SessionMessage,
  type UncommittedTool,
  decodeSessionMessages,
  decodeUncommittedTools,
} from './history';
import {
  type AgentInfo,
  type AskQuestion,
  type BranchTarget,
  decodeAgentInfo,
  decodeAskQuestion,
  decodeBranchTarget,
} from './models';

// ============================================================
// Common meta
// ============================================================

/** Metadata every event carries (`wing/event/base.py::WingEvent`). */
export interface EventMeta {
  /** UTC ISO-8601 timestamp string. */
  readonly created_at: string;
  /** Request correlation id (always generated by the backend). */
  readonly request_id: string;
  /** Owning session; `null` for the few events emitted before a session exists. */
  readonly session_id: string | null;
  /**
   * Chain node id.
   *
   * `wire_dump` strips it unless the event declares one (the four turn-level
   * events: assistant_turn / tool_result_turn / turn_result / session_init), so
   * a missing value decodes to `null` — "unknown", never a fabricated id. (The
   * Rust mirror does not carry `uuid` on every variant at all; being uniformly
   * nullable is the additive version of the same tolerance.)
   */
  readonly uuid: string | null;
}

// ============================================================
// Events
// ============================================================

/** `error` — the failure event; replaces scattered status codes. */
export interface ErrorEvent extends EventMeta {
  readonly type: 'error';
  readonly status_code: number;
  readonly message: string;
  readonly error_code: string | null;
  readonly detail: string | null;
}

/** `delivered` — transport ack: the request reached the backend. */
export interface DeliveredEvent extends EventMeta {
  readonly type: 'delivered';
}

/** `notice` level (unknown values degrade to `info`, like the Rust mirror). */
export const NOTICE_LEVELS = ['info', 'warning', 'error'] as const;
export type NoticeLevel = (typeof NOTICE_LEVELS)[number];

/**
 * `notice` — a one-shot hint that is **not** an error and **not** end-of-turn
 * (e.g. "LLM call failed, retrying in N s"). A frontend must not finish the turn
 * on it. Broadcast-only: never replayed from history.
 */
export interface NoticeEvent extends EventMeta {
  readonly type: 'notice';
  readonly level: NoticeLevel;
  readonly message: string;
  readonly attempt: number | null;
  readonly max_attempts: number | null;
  readonly retry_in_s: number | null;
}

/** `text` — assistant text delta. */
export interface TextEvent extends EventMeta {
  readonly type: 'text';
  readonly content: string;
}

/** `reasoning` — thinking / reasoning delta. */
export interface ReasoningEvent extends EventMeta {
  readonly type: 'reasoning';
  readonly content: string;
}

/** `tool_call` — a tool call starts executing (authoritative parsed args). */
export interface ToolCallEvent extends EventMeta {
  readonly type: 'tool_call';
  readonly tool_name: string;
  readonly tool_args: JsonObject;
  readonly tool_call_id: string;
}

/**
 * `tool_call_stream` — raw args text fragment while the LLM is still generating.
 *
 * Fragments accumulate into the full args text; the backend never parses partial
 * JSON, so neither does `src/core` — that belongs to the host's renderers.
 */
export interface ToolCallStreamEvent extends EventMeta {
  readonly type: 'tool_call_stream';
  readonly tool_call_id: string;
  readonly tool_name: string;
  readonly args_fragment: string;
  readonly is_final: boolean;
}

/** `tool_call_result` — a tool finished (live only; `persist = false`). */
export interface ToolCallResultEvent extends EventMeta {
  readonly type: 'tool_call_result';
  readonly tool_name: string;
  readonly tool_args: JsonObject;
  readonly tool_call_id: string;
  readonly tool_result: string;
  readonly tool_success: boolean;
  readonly model: string;
}

/** `llm_call_metrics` — usage / latency of one LLM call. */
export interface LlmCallMetricsEvent extends EventMeta {
  readonly type: 'llm_call_metrics';
  readonly model: string;
  readonly prompt_tokens: number;
  readonly completion_tokens: number;
  readonly cached_tokens: number;
  readonly first_chunk_rt_ms: number;
  readonly tokens_per_sec: number;
  /** Protocol-native stop reason (`end_turn` / `max_tokens` / `tool_use` / `stop` / `length`). */
  readonly stop_reason: string | null;
}

/**
 * `ask` — the agent needs user input.
 *
 * Two shapes coexist: the multi-question `AskUserQuestion` tool fills
 * `questions`, the legacy Bash-confirmation path fills `question` + `choices`.
 * `tool_call_id` addresses the reply (`ClientRequest.tool_call_id`).
 */
export interface AskEvent extends EventMeta {
  readonly type: 'ask';
  readonly tool_call_id: string;
  readonly questions: readonly AskQuestion[];
  readonly question: string;
  readonly choices: readonly string[];
  readonly required: boolean;
}

/** `done` — the agent loop finished. */
export interface DoneEvent extends EventMeta {
  readonly type: 'done';
}

/** `turn_started` — the agent started processing a user message. */
export interface TurnStartedEvent extends EventMeta {
  readonly type: 'turn_started';
}

/**
 * `user_message_accepted` — the message was injected into the model context.
 *
 * `origin_request_id` is the `ClientRequest.request_id` the client submitted, so
 * the host can move its local echo from "queued" to "sent".
 */
export interface UserMessageAcceptedEvent extends EventMeta {
  readonly type: 'user_message_accepted';
  readonly content: string;
  readonly origin_request_id: string;
}

/** `diff_content` — diff payload for Write / Edit / BetterEdit. */
export interface DiffContentEvent extends EventMeta {
  readonly type: 'diff_content';
  readonly path: string;
  /** `null` means "new file" (whole file is green). */
  readonly old_text: string | null;
  readonly new_text: string;
  /** 1-based absolute line number of the window's first line in the old revision. */
  readonly old_start_line: number;
  readonly new_start_line: number;
  readonly tool_call_id: string;
}

/** `assistant_turn` — turn-level complete assistant message (stdio consumers). */
export interface AssistantTurnEvent extends EventMeta {
  readonly type: 'assistant_turn';
  readonly content_blocks: readonly JsonObject[];
  readonly model: string;
  readonly stop_reason: string | null;
  readonly usage: JsonObject | null;
}

/** `tool_result_turn` — turn-level tool result (stdio consumers). */
export interface ToolResultTurnEvent extends EventMeta {
  readonly type: 'tool_result_turn';
  readonly tool_use_id: string;
  readonly tool_name: string;
  readonly content: string;
  readonly is_error: boolean;
}

/** `turn_result` — final result of a whole agent loop. */
export interface TurnResultEvent extends EventMeta {
  readonly type: 'turn_result';
  readonly subtype: string;
  readonly is_error: boolean;
  readonly result: string | null;
  readonly num_turns: number;
  readonly duration_ms: number;
  readonly usage: JsonObject | null;
  readonly errors: readonly string[];
}

/**
 * `sync_session` — the full replay payload pushed on subscribe / fork / rewind.
 *
 * Consumers MUST assemble in the documented order
 * `messages → uncommitted → uncommitted_tools → events` and then continue with
 * the live stream. `events` are decoded into {@link WingEvent}s on purpose: the
 * replay facts (diff / ask / interrupted / error / compact_done) therefore take
 * the *same* reduction path as live events in the host.
 */
export interface SyncSessionEvent extends EventMeta {
  readonly type: 'sync_session';
  readonly session_id: string;
  readonly messages: readonly SessionMessage[];
  readonly uncommitted: SessionMessage | null;
  readonly uncommitted_tools: readonly UncommittedTool[];
  readonly events: readonly WingEvent[];
  /** Turn start time (UTC ISO) — restore an in-flight turn's elapsed time. */
  readonly turn_started_at: string | null;
  readonly agent: AgentInfo | null;
  readonly name: string | null;
  readonly draft: string | null;
}

/** `session_init` — authoritative session state after subscribe (stdio mode). */
export interface SessionInitEvent extends EventMeta {
  readonly type: 'session_init';
  readonly tools: readonly string[];
  readonly model: string;
  readonly permission_mode: string;
  readonly cwd: string;
}

/** `interrupted` — the user aborted the running turn. */
export interface InterruptedEvent extends EventMeta {
  readonly type: 'interrupted';
}

/** `compact_done` — manual compaction finished. */
export interface CompactDoneEvent extends EventMeta {
  readonly type: 'compact_done';
  readonly original_tokens: number;
  readonly compressed_tokens: number;
  readonly model: string;
}

/** `session_state_changed` — one event for model / thinking / effort / yolo / title / agent. */
export interface SessionStateChangedEvent extends EventMeta {
  readonly type: 'session_state_changed';
  readonly model: string | null;
  readonly thinking: boolean | null;
  readonly reasoning_effort: string | null;
  readonly yolo: boolean | null;
  readonly title: string | null;
  readonly agent: string | null;
}

/** `context_stats` — context window usage, emitted after every LLM turn. */
export interface ContextStatsEvent extends EventMeta {
  readonly type: 'context_stats';
  readonly message_count: number;
  readonly total_tokens: number;
  readonly context_window_tokens: number;
  readonly system_prompt_parts: readonly string[];
}

/** `branch_targets` — rewind / fork candidates. */
export interface BranchTargetsEvent extends EventMeta {
  readonly type: 'branch_targets';
  readonly targets: readonly BranchTarget[];
}

/** Every event type this client knows how to decode. */
export type KnownWingEvent =
  | ErrorEvent
  | DeliveredEvent
  | NoticeEvent
  | TextEvent
  | ReasoningEvent
  | ToolCallEvent
  | ToolCallStreamEvent
  | ToolCallResultEvent
  | LlmCallMetricsEvent
  | AskEvent
  | DoneEvent
  | TurnStartedEvent
  | UserMessageAcceptedEvent
  | DiffContentEvent
  | AssistantTurnEvent
  | ToolResultTurnEvent
  | TurnResultEvent
  | SyncSessionEvent
  | SessionInitEvent
  | InterruptedEvent
  | CompactDoneEvent
  | SessionStateChangedEvent
  | ContextStatsEvent
  | BranchTargetsEvent;

/** The discriminated tag of every known event. */
export type KnownEventType = KnownWingEvent['type'];

/**
 * An event this client cannot represent as a typed model.
 *
 * Either the `type` is unknown (forward compatibility: a newer gateway) or a
 * *known* type arrived with a payload that failed validation. Both are surfaced
 * the same way — with the raw payload — so the host can log / ignore them, but it
 * can never receive a half-filled typed event.
 *
 * The `raw` field doubles as the runtime discriminant: no known event has it, so
 * {@link isKnownEvent} can narrow the union without inspecting the payload.
 */
export interface UnknownWingEvent {
  /** Whatever the frame declared (empty string when the payload had no `type`). */
  readonly type: string;
  /** Routing convenience: `session_id` extracted from the payload when present. */
  readonly session_id: string | null;
  /** The untouched payload. */
  readonly raw: JsonObject;
}

/** Anything the gateway can push over the event stream. */
export type WingEvent = KnownWingEvent | UnknownWingEvent;

// ============================================================
// Decoders
// ============================================================

type EventDecoder<T extends KnownWingEvent> = (payload: JsonObject, meta: EventMeta) => T;

function readMeta(payload: JsonObject): EventMeta {
  return {
    created_at: stringOr(payload, 'created_at', ''),
    request_id: stringOr(payload, 'request_id', ''),
    session_id: optString(payload, 'session_id'),
    uuid: optString(payload, 'uuid'),
  };
}

/** Decode the replay facts of `sync_session.events` with the live-event decoder. */
function decodeEventList(object: JsonObject, key: string): WingEvent[] {
  return readJsonArray(object, key)
    .filter(isJsonObject)
    .map((value) => decodeWingEvent(value));
}

const decodeError: EventDecoder<ErrorEvent> = (payload, meta) => ({
  ...meta,
  type: 'error',
  status_code: numberOr(payload, 'status_code', 500),
  message: stringOr(payload, 'message', ''),
  error_code: optString(payload, 'error_code'),
  detail: optString(payload, 'detail'),
});

const decodeDelivered: EventDecoder<DeliveredEvent> = (_payload, meta) => ({
  ...meta,
  type: 'delivered',
});

const decodeNotice: EventDecoder<NoticeEvent> = (payload, meta) => ({
  ...meta,
  type: 'notice',
  level: enumOr(payload, 'level', NOTICE_LEVELS, 'info'),
  message: stringOr(payload, 'message', ''),
  attempt: optNumber(payload, 'attempt'),
  max_attempts: optNumber(payload, 'max_attempts'),
  retry_in_s: optNumber(payload, 'retry_in_s'),
});

const decodeText: EventDecoder<TextEvent> = (payload, meta) => ({
  ...meta,
  type: 'text',
  content: reqString(payload, 'content'),
});

const decodeReasoning: EventDecoder<ReasoningEvent> = (payload, meta) => ({
  ...meta,
  type: 'reasoning',
  content: reqString(payload, 'content'),
});

const decodeToolCall: EventDecoder<ToolCallEvent> = (payload, meta) => ({
  ...meta,
  type: 'tool_call',
  tool_name: reqString(payload, 'tool_name'),
  tool_args: requireObject(payload, 'tool_args'),
  tool_call_id: reqString(payload, 'tool_call_id'),
});

const decodeToolCallStream: EventDecoder<ToolCallStreamEvent> = (payload, meta) => ({
  ...meta,
  type: 'tool_call_stream',
  tool_call_id: reqString(payload, 'tool_call_id'),
  tool_name: reqString(payload, 'tool_name'),
  args_fragment: stringOr(payload, 'args_fragment', ''),
  is_final: booleanOr(payload, 'is_final', false),
});

const decodeToolCallResult: EventDecoder<ToolCallResultEvent> = (payload, meta) => ({
  ...meta,
  type: 'tool_call_result',
  tool_name: reqString(payload, 'tool_name'),
  tool_args: requireObject(payload, 'tool_args'),
  tool_call_id: reqString(payload, 'tool_call_id'),
  tool_result: reqString(payload, 'tool_result'),
  tool_success: reqBoolean(payload, 'tool_success'),
  model: stringOr(payload, 'model', ''),
});

const decodeLlmCallMetrics: EventDecoder<LlmCallMetricsEvent> = (payload, meta) => ({
  ...meta,
  type: 'llm_call_metrics',
  model: stringOr(payload, 'model', ''),
  prompt_tokens: reqNumber(payload, 'prompt_tokens'),
  completion_tokens: reqNumber(payload, 'completion_tokens'),
  cached_tokens: reqNumber(payload, 'cached_tokens'),
  first_chunk_rt_ms: reqNumber(payload, 'first_chunk_rt_ms'),
  tokens_per_sec: reqNumber(payload, 'tokens_per_sec'),
  stop_reason: optString(payload, 'stop_reason'),
});

const decodeAsk: EventDecoder<AskEvent> = (payload, meta) => ({
  ...meta,
  type: 'ask',
  tool_call_id: stringOr(payload, 'tool_call_id', ''),
  questions: decodeEach(readJsonArray(payload, 'questions'), decodeAskQuestion),
  question: stringOr(payload, 'question', ''),
  choices: readStringArray(payload, 'choices'),
  required: booleanOr(payload, 'required', false),
});

const decodeDone: EventDecoder<DoneEvent> = (_payload, meta) => ({ ...meta, type: 'done' });

const decodeTurnStarted: EventDecoder<TurnStartedEvent> = (_payload, meta) => ({
  ...meta,
  type: 'turn_started',
});

const decodeUserMessageAccepted: EventDecoder<UserMessageAcceptedEvent> = (payload, meta) => ({
  ...meta,
  type: 'user_message_accepted',
  content: reqString(payload, 'content'),
  origin_request_id: stringOr(payload, 'origin_request_id', ''),
});

const decodeDiffContent: EventDecoder<DiffContentEvent> = (payload, meta) => ({
  ...meta,
  type: 'diff_content',
  path: reqString(payload, 'path'),
  old_text: optString(payload, 'old_text'),
  new_text: reqString(payload, 'new_text'),
  old_start_line: numberOr(payload, 'old_start_line', 1),
  new_start_line: numberOr(payload, 'new_start_line', 1),
  tool_call_id: stringOr(payload, 'tool_call_id', ''),
});

const decodeAssistantTurn: EventDecoder<AssistantTurnEvent> = (payload, meta) => ({
  ...meta,
  type: 'assistant_turn',
  content_blocks: reqJsonArray(payload, 'content_blocks').filter(isJsonObject),
  model: stringOr(payload, 'model', ''),
  stop_reason: optString(payload, 'stop_reason'),
  usage: optJsonObject(payload, 'usage'),
});

const decodeToolResultTurn: EventDecoder<ToolResultTurnEvent> = (payload, meta) => ({
  ...meta,
  type: 'tool_result_turn',
  tool_use_id: reqString(payload, 'tool_use_id'),
  tool_name: reqString(payload, 'tool_name'),
  content: reqString(payload, 'content'),
  is_error: booleanOr(payload, 'is_error', false),
});

const decodeTurnResult: EventDecoder<TurnResultEvent> = (payload, meta) => ({
  ...meta,
  type: 'turn_result',
  subtype: stringOr(payload, 'subtype', 'success'),
  is_error: booleanOr(payload, 'is_error', false),
  result: optString(payload, 'result'),
  num_turns: numberOr(payload, 'num_turns', 0),
  duration_ms: numberOr(payload, 'duration_ms', 0),
  usage: optJsonObject(payload, 'usage'),
  errors: readStringArray(payload, 'errors'),
});

const decodeSyncSession: EventDecoder<SyncSessionEvent> = (payload, meta) => ({
  ...meta,
  type: 'sync_session',
  session_id: reqString(payload, 'session_id'),
  messages: decodeSessionMessages(readJsonArray(payload, 'messages')),
  uncommitted: decodeSingleMessage(payload, 'uncommitted'),
  uncommitted_tools: decodeUncommittedTools(readJsonArray(payload, 'uncommitted_tools')),
  events: decodeEventList(payload, 'events'),
  turn_started_at: optString(payload, 'turn_started_at'),
  agent: decodeAgentInfo(payload['agent']),
  name: optString(payload, 'name'),
  draft: optString(payload, 'draft'),
});

const decodeSessionInit: EventDecoder<SessionInitEvent> = (payload, meta) => ({
  ...meta,
  type: 'session_init',
  tools: readStringArray(payload, 'tools'),
  model: stringOr(payload, 'model', ''),
  permission_mode: stringOr(payload, 'permission_mode', 'default'),
  cwd: stringOr(payload, 'cwd', ''),
});

const decodeInterrupted: EventDecoder<InterruptedEvent> = (_payload, meta) => ({
  ...meta,
  type: 'interrupted',
});

const decodeCompactDone: EventDecoder<CompactDoneEvent> = (payload, meta) => ({
  ...meta,
  type: 'compact_done',
  // Both token counts are required in Python (`state_change.py`: no default), so
  // a payload without them is malformed — guessing `0` would show "0 → 0 tokens"
  // for a compaction that may have saved 90k. Strict fields degrade to
  // `UnknownWingEvent` instead of inventing numbers (see the policy notes above).
  original_tokens: reqNumber(payload, 'original_tokens'),
  compressed_tokens: reqNumber(payload, 'compressed_tokens'),
  model: stringOr(payload, 'model', ''),
});

const decodeSessionStateChanged: EventDecoder<SessionStateChangedEvent> = (payload, meta) => ({
  ...meta,
  type: 'session_state_changed',
  model: optString(payload, 'model'),
  thinking: optionalBoolean(payload, 'thinking'),
  reasoning_effort: optString(payload, 'reasoning_effort'),
  yolo: optionalBoolean(payload, 'yolo'),
  title: optString(payload, 'title'),
  agent: optString(payload, 'agent'),
});

const decodeContextStats: EventDecoder<ContextStatsEvent> = (payload, meta) => ({
  ...meta,
  type: 'context_stats',
  message_count: reqNumber(payload, 'message_count'),
  total_tokens: reqNumber(payload, 'total_tokens'),
  context_window_tokens: numberOr(payload, 'context_window_tokens', 0),
  system_prompt_parts: readStringArray(payload, 'system_prompt_parts'),
});

const decodeBranchTargets: EventDecoder<BranchTargetsEvent> = (payload, meta) => ({
  ...meta,
  type: 'branch_targets',
  targets: decodeEach(readJsonArray(payload, 'targets'), decodeBranchTarget),
});

/**
 * The decoder table doubles as the runtime registry.
 *
 * `Record<KnownEventType, …>` is deliberate: adding a variant to
 * {@link KnownWingEvent} without adding a decoder is a compile error, and
 * {@link KNOWN_EVENT_TYPES} is derived from the same object, so the runtime
 * registry can never drift from the union.
 */
const DECODERS: Record<KnownEventType, EventDecoder<KnownWingEvent>> = {
  error: decodeError,
  delivered: decodeDelivered,
  notice: decodeNotice,
  text: decodeText,
  reasoning: decodeReasoning,
  tool_call: decodeToolCall,
  tool_call_stream: decodeToolCallStream,
  tool_call_result: decodeToolCallResult,
  llm_call_metrics: decodeLlmCallMetrics,
  ask: decodeAsk,
  done: decodeDone,
  turn_started: decodeTurnStarted,
  user_message_accepted: decodeUserMessageAccepted,
  diff_content: decodeDiffContent,
  assistant_turn: decodeAssistantTurn,
  tool_result_turn: decodeToolResultTurn,
  turn_result: decodeTurnResult,
  sync_session: decodeSyncSession,
  session_init: decodeSessionInit,
  interrupted: decodeInterrupted,
  compact_done: decodeCompactDone,
  session_state_changed: decodeSessionStateChanged,
  context_stats: decodeContextStats,
  branch_targets: decodeBranchTargets,
};

/** Every `type` this build understands (compare with Python's `EVENT_TYPES`). */
export const KNOWN_EVENT_TYPES: ReadonlySet<string> = new Set(Object.keys(DECODERS));

/**
 * Type guard on the *declared* type: this build knows that `type` string.
 *
 * Note the difference from {@link isKnownEvent}: a known type whose payload
 * failed validation is still "a known type" here (the frame said `text`), but it
 * decoded into the fallback variant.
 */
export function isKnownEventType(type: string): type is KnownEventType {
  return KNOWN_EVENT_TYPES.has(type);
}

/** Type guard: the event decoded into a typed model (not the fallback variant). */
export function isKnownEvent(event: WingEvent): event is KnownWingEvent {
  return !('raw' in event);
}

/**
 * Decode one payload into an event. **Never throws.**
 *
 * Unknown types and payloads that fail validation both come back as an
 * {@link UnknownWingEvent} carrying the raw payload.
 */
export function decodeWingEvent(payload: unknown): WingEvent {
  if (!isJsonObject(payload)) {
    return { type: '', session_id: null, raw: {} };
  }
  const type = payload['type'];
  if (typeof type !== 'string' || !isKnownEventType(type)) {
    return {
      type: typeof type === 'string' ? type : '',
      session_id: optString(payload, 'session_id'),
      raw: payload,
    };
  }
  const decoder = DECODERS[type];
  try {
    return decoder(payload, readMeta(payload));
  } catch (cause) {
    if (!(cause instanceof ProtocolDecodeError)) {
      throw cause;
    }
    return { type, session_id: optString(payload, 'session_id'), raw: payload };
  }
}

// ============================================================
// Local helpers
// ============================================================

function requireObject(payload: JsonObject, key: string): JsonObject {
  const value = payload[key];
  if (!isJsonObject(value)) {
    throw new ProtocolDecodeError(`field "${key}" must be an object`);
  }
  return value;
}

/** Nullable boolean (`SessionStateChangedEvent.thinking` / `.yolo`). */
function optionalBoolean(payload: JsonObject, key: string): boolean | null {
  const value = payload[key];
  if (value === undefined || value === null) {
    return null;
  }
  return reqBoolean(payload, key);
}

/** `uncommitted` is a single message projection or `null`. */
function decodeSingleMessage(payload: JsonObject, key: string): SessionMessage | null {
  const value = payload[key];
  if (value === undefined || value === null) {
    return null;
  }
  const decoded = decodeSessionMessages([value]);
  return decoded[0] ?? null;
}
