//! ConnectResponse — the first message Gateway sends after WS handshake.
//!
//! Mirrors: wing_gateway/protocol.py ConnectResponse

use serde::Deserialize;
use serde::Serialize;

/// Sent by Gateway immediately after WebSocket connection is established.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectResponse {
    /// Always "connected".
    #[serde(rename = "type", default = "default_type")]
    pub msg_type: String,
    /// The client id generated by Gateway.
    pub client_id: String,
}

fn default_type() -> String {
    "connected".into()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deserialize_connect_response() {
        let json = r#"{"type": "connected", "client_id": "xyz789"}"#;
        let resp: ConnectResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.client_id, "xyz789");
        assert_eq!(resp.msg_type, "connected");
    }
}
