# libs/core/hatch_build.py — hatchling 构建钩子：注入构建信息

"""构建/安装时写入 ``wing/_build_info.py``（版本 + commit hash）。

commit 解析顺序（与 Rust ``crates/wing/build.rs`` 同一约定）：

1. ``WING_COMMIT_HASH`` 环境变量（CI 传入 ``github.sha``，截短到 7 位）；
2. 构建时执行 ``git rev-parse HEAD``——仅构建期，运行期不做任何 git 调用；
3. ``None``（无 git 的构建，如从 sdist 构建）。

版本取构建时的项目版本（hatch-vcs 从 git tag 推导，CI 可用
``SETUPTOOLS_SCM_PRETEND_VERSION`` 覆盖）。运行期由 ``wing/build_info.py``
只读消费：发版 wheel 与开发环境的 ``pip install libs/core`` 都能报告
构建时的 commit。
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

#: 生成文件相对项目根的路径（沿用 hatch-vcs ``version-file`` 的约定）。
GENERATED_FILE = "wing/_build_info.py"

#: 短 hash 长度——与 ``git rev-parse --short`` / Rust build.rs 一致。
COMMIT_LENGTH = 7

_HEADER = (
    "# file generated by hatch_build.py\n"
    "# don't change, don't track in version control\n"
)


def resolve_commit(root: Path) -> str | None:
    """解析构建时的 commit hash（短）；拿不到返回 None。"""
    raw = os.environ.get("WING_COMMIT_HASH", "").strip()
    if not raw:
        try:
            proc = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=root,
                capture_output=True,
                text=True,
                check=True,
            )
        except (OSError, subprocess.CalledProcessError):
            return None
        raw = proc.stdout.strip()
    return raw[:COMMIT_LENGTH] or None


def render_build_info(version: str, commit: str | None) -> str:
    """渲染生成模块内容——输出确定性，内容不变则不重写文件。"""
    return f"{_HEADER}\nversion: str = {version!r}\ncommit: str | None = {commit!r}\n"


class BuildInfoHook(BuildHookInterface):
    """把构建信息写进 ``wing/_build_info.py``，并声明为 wheel 产物。"""

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        target = Path(self.root) / GENERATED_FILE
        content = render_build_info(
            self.metadata.version, resolve_commit(Path(self.root))
        )
        # 内容不变则保留原文件（mtime 稳定，避免无谓触发下游重建判定）。
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            target.write_text(content, encoding="utf-8")
        # 生成文件不在 VCS 中，显式声明才会被收进 wheel（同 hatch-vcs 做法）。
        build_data["artifacts"].append(f"/{GENERATED_FILE}")
